version: '3.7'
services:
  db:
    image: mongo:5
    container_name: db
    networks:
        localnet:
            ipv4_address: 172.20.0.2
    restart: always
    volumes:
      - /home/db:/data/db
      - /home/dbexport:/export

  redis:
    networks:
        localnet:
            ipv4_address: 172.20.0.3
    image: redis:7.0.12-alpine
    container_name: redis
    restart: always

  api:
    image: 'api:latest'
    restart: unless-stopped
    container_name: api
    networks:
        localnet:
            ipv4_address: 172.20.0.4
    environment:
      - PORT=8686
      - JWT_SECRET=a?S6zjgbZxm7Fv?rd#h?AEM*
      - DB_URI=mongodb://db/trans
      - IS_DOCKER=true
    build: api/.
    working_dir: /var/www/trans-api
    volumes:
      - /home/uploads:/var/www/trans-api/public/uploads
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  fe:
    image: 'node:16-alpine'
    restart: unless-stopped
    networks:
        localnet:
            ipv4_address: 172.20.0.5
    environment:
      - PORT=8687
      - API_ROOT=https://api.tamsonyachting.com
      - baseUrl=https://api.tamsonyachting.com
      - NODE_OPTIONS="–max_old_space_size=2048"
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    container_name: fe
    volumes:
      - /home/www/fe:/node
    command: ["yarn", "start"]
    #command: sleep 10000

    #build: fe/.
    working_dir: /node

  admin:
    image: 'node:14.19.1-alpine'
    restart: unless-stopped
    networks:
        localnet:
            ipv4_address: 172.20.0.6
    container_name: admin
    volumes:
      - /home/www/admin:/node
    command: ["yarn", "start"]
    #command: sleep 10000

    environment:
      - REACT_APP_TOKEN_NAME=trans-token
      - REACT_APP_BACKEND_ENDPOINT=https://api.tamsonyachting.com
      - PORT=8688
    #build: admin/.
    working_dir: /node

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    networks:
        localnet:
            ipv4_address: 172.20.0.7
    container_name: proxy
    restart: unless-stopped
    ports:
      - '80:80'
     # - '81:81'
      - '443:443'
    volumes:
      - /home/proxy/data:/data
      - /home/proxy/letsencrypt:/etc/letsencrypt
networks:
  localnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
volumes:
  apiUploads: {}


